# prototype-kicad-library-ci

# File: .github/workflows/ci.yml
# Description: GitHub Actions CI workflow for the prototype-kicad-library-ci repository.

name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    analyze-static-shellcheck:
        name: Analyze (static) - shellcheck
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - name: Analyze
              shell: bash
              run: ./ci/analyze --analyzer shellcheck
