# prototype-kicad-library-ci

# File: .github/workflows/ci.yml
# Description: GitHub Actions CI workflow for the prototype-kicad-library-ci repository.

name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    analyze-static-shellcheck:
        name: Analyze (static) - shellcheck
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - name: Analyze
              shell: bash
              run: ./ci/analyze --analyzer shellcheck

    check-klc-compliance-footprints:
        name: Check KLC compliance - footprints
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: recursive
            - name: Check KLC compliance
              shell: bash
              run: ./ci/check-klc-compliance --check-footprints

    check-klc-compliance-symbols:
        name: Check KLC compliance - symbols
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: recursive
            - name: Check KLC compliance
              shell: bash
              run: ./ci/check-klc-compliance --check-symbols
